// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oazptcguznzadabfjgbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9henB0Y2d1em56YWRhYmZqZ2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDY1ODIsImV4cCI6MjA2MTMyMjU4Mn0.Np5I5HfcURQf8tcd5_zIuT8K83OdHCQstd24Aj-edp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);